// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByhMMjXaQVKFYnND6MX_rs5Qi-RcICEgY',
    appId: '1:931067884036:web:206d9a484b28223c27fb51',
    messagingSenderId: '931067884036',
    projectId: 'flutter-auth-2d7c1',
    authDomain: 'flutter-auth-2d7c1.firebaseapp.com',
    storageBucket: 'flutter-auth-2d7c1.firebasestorage.app',
    measurementId: 'G-PWTEZEP5HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIN69SamrFL_RXNdZqRifujBRz4faJ09s',
    appId: '1:931067884036:android:2e5cd82b234c8a4227fb51',
    messagingSenderId: '931067884036',
    projectId: 'flutter-auth-2d7c1',
    storageBucket: 'flutter-auth-2d7c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjd7tDa7bieQBNmkDZ28gX8ESz8LXZ2s',
    appId: '1:931067884036:ios:d4f3a7b10c4a8c9e27fb51',
    messagingSenderId: '931067884036',
    projectId: 'flutter-auth-2d7c1',
    storageBucket: 'flutter-auth-2d7c1.firebasestorage.app',
    iosClientId: '931067884036-3i2uaj5ir56qd4sndemq9krqm7eifs4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaesFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjd7tDa7bieQBNmkDZ28gX8ESz8LXZ2s',
    appId: '1:931067884036:ios:d4f3a7b10c4a8c9e27fb51',
    messagingSenderId: '931067884036',
    projectId: 'flutter-auth-2d7c1',
    storageBucket: 'flutter-auth-2d7c1.firebasestorage.app',
    iosClientId: '931067884036-3i2uaj5ir56qd4sndemq9krqm7eifs4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaesFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByhMMjXaQVKFYnND6MX_rs5Qi-RcICEgY',
    appId: '1:931067884036:web:c2e145ed01b89a0427fb51',
    messagingSenderId: '931067884036',
    projectId: 'flutter-auth-2d7c1',
    authDomain: 'flutter-auth-2d7c1.firebaseapp.com',
    storageBucket: 'flutter-auth-2d7c1.firebasestorage.app',
    measurementId: 'G-SHQEQMEMS1',
  );
}
